name: Check for Tag

on: push

jobs:
  check-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for Tag
        run: |
          TAG="0.1"
          if [ $(git tag -l "${TAG}") ]; then
            echo "Tag ${TAG} exists"
          else
            echo "Tag ${TAG} does not exist"
          fi
